# Generated by Django 3.2.7 on 2021-11-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_namespace_submission_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='ng_link_type',
            field=models.CharField(choices=[('path', 'Path Layer'), ('point', 'Annotation Layer'), ('pregen', 'Pregenerated')], default='point', max_length=50),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='submission_method',
            field=models.CharField(choices=[('submit', 'Submit Button'), ('forced_choice', 'Yes/No/Maybe Button')], default='submit', max_length=50),
        ),
    ]
