# Generated by Django 3.2.7 on 2021-11-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('namespace', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('ng_link_type', models.CharField(max_length=50)),
            ],
        ),
    ]
