# Generated by Django 3.2.7 on 2022-01-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20211206_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_method', models.CharField(choices=[('submit', 'Submit Button'), ('forced_choice', 'Yes/No/Maybe Button')], default='submit', max_length=50)),
                ('param_source', models.CharField(choices=[('0.5', 'Alpha Default'), ('0.3', 'Alpha 3D')], default='0.5', max_length=300)),
            ],
        ),
    ]
