# Generated by Django 3.2.7 on 2022-01-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20211206_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='ng_link_type',
            field=models.CharField(choices=[('path', 'Path Layer'), ('point', 'Annotation Layer'), ('pregen', 'Pregenerated')], default='pregen', max_length=50),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='pcg_source',
            field=models.CharField(choices=[('https://minnie.microns-daf.com/segmentation/table/minnie3_v1', 'Minnie65'), ('https://minnie.microns-daf.com/segmentation/table/pinky_v2_microns_sandbox', 'Pinky')], default='https://minnie.microns-daf.com/segmentation/table/minnie3_v1', max_length=300),
        ),
    ]
