# Generated by Django 3.2.7 on 2022-01-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='param_source',
        ),
        migrations.RemoveField(
            model_name='config',
            name='submission_method',
        ),
        migrations.AddField(
            model_name='config',
            name='alpha_3d',
            field=models.CharField(default=0.3, max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='alpha_selected',
            field=models.CharField(default=0.6, max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='user',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
