# Generated by Django 3.2.7 on 2021-12-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_auto_20211117_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='image_source',
            field=models.CharField(choices=[('https://bossdb-open-data.s3.amazonaws.com/iarpa_microns/minnie/minnie65/em', 'Minnie65'), ('gs://microns_public_datasets/pinky100_v0/son_of_alignment_v15_rechunked', 'Pinky')], default='https://bossdb-open-data.s3.amazonaws.com/iarpa_microns/minnie/minnie65/em', max_length=300),
        ),
        migrations.AddField(
            model_name='namespace',
            name='pcg_source',
            field=models.CharField(choices=[('https://minnie.microns-daf.com/segmentation/table/minnie3_v1', 'Minnie65'), ('https://global.daf-apis.com/info/datastack/pinky_sandbox', 'Pinky')], default='https://minnie.microns-daf.com/segmentation/table/minnie3_v1', max_length=300),
        ),
    ]
