# Generated by Django 3.2.7 on 2022-02-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_auto_20220125_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='submission_method',
            field=models.CharField(choices=[('submit', 'Submit Button'), ('forced_choice', 'Yes/No/Maybe Button'), ('decide_and_submit', 'Decide and Submit Button')], default='submit', max_length=50),
        ),
    ]
