# Generated by Django 3.2.7 on 2021-12-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_auto_20211202_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namespace',
            old_name='pcg_source',
            new_name='ChunkedGraph Source',
        ),
        migrations.RenameField(
            model_name='namespace',
            old_name='image_source',
            new_name='EM Image Source',
        ),
    ]
