# Generated by Django 3.2.7 on 2022-02-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_alter_namespace_submission_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='track_operation_ids',
            field=models.BooleanField(default=True),
        ),
    ]
