# Generated by Django 3.2.7 on 2022-01-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_auto_20220104_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
