# Generated by Django 3.2.7 on 2021-12-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_auto_20211202_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namespace',
            old_name='EM Image Source',
            new_name='img_source',
        ),
        migrations.RenameField(
            model_name='namespace',
            old_name='ChunkedGraph Source',
            new_name='pcg_source',
        ),
    ]
