# Generated by Django 3.2.7 on 2022-02-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_namespace_track_operation_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='track_operation_ids',
            field=models.BooleanField(default=True),
        ),
    ]
