# Generated by Django 3.2.7 on 2022-02-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_namespace_track_operation_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='namespace_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
