# Generated by Django 3.2.7 on 2022-02-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_namespace_namespace_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namespace',
            name='namespace_enabled',
        ),
    ]
