# Generated by Django 3.2.7 on 2021-12-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_auto_20211202_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='pcg_source',
            field=models.CharField(choices=[('https://minnie.microns-daf.com/segmentation/table/minnie3_v1', 'Minnie65'), ('https://minnie.microns-daf.com/segmentation/table/pinky_nf_v2', 'Pinky')], default='https://minnie.microns-daf.com/segmentation/table/minnie3_v1', max_length=300),
        ),
    ]
