# Generated by Django 3.2.7 on 2022-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_remove_namespace_namespace_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='namespace_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
