# Generated by Django 3.2.7 on 2022-03-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_auto_20220302_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namespace',
            old_name='max_number_of_tasks_per_user',
            new_name='max_number_of_pending_tasks_per_user',
        ),
    ]
