# Generated by Django 3.2.7 on 2022-05-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_auto_20220322_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='submission_method',
            field=models.CharField(choices=[('submit', 'Submit Button'), ('forced_choice', 'Forced Choice'), ('yes_no_maybe', 'Y/N/M'), ('decide_and_submit', 'Decide and Submit Button')], default='submit', max_length=50),
        ),
    ]
