# Generated by Django 3.2.7 on 2022-05-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0010_alter_namespace_submission_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namespace",
            name="submission_method",
            field=models.CharField(
                choices=[
                    ("submit", "Submit Button"),
                    ("forced_choice", "Forced Choice"),
                    ("yes_no", "Y/N"),
                    ("decide_and_submit", "Decide and Submit Button"),
                ],
                default="submit",
                max_length=50,
            ),
        ),
    ]
