# Generated by Django 3.2.7 on 2022-06-10 16:37

from django.db import migrations, models
import workspace.validators


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_auto_20220609_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcedchoicebutton',
            name='submission_value',
            field=models.CharField(max_length=100, validators=[workspace.validators.validate_submission_value]),
        ),
    ]
