# Generated by Django 3.2.7 on 2022-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0014_forcedchoicebutton_hotkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="namespace",
            name="track_selected_segments",
            field=models.BooleanField(default=False),
        ),
    ]
