# Generated by Django 3.2.7 on 2023-01-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0016_forcedchoicebuttongroup_number_of_selected_segments_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='allow_users_to_skip_tasks',
            field=models.BooleanField(default=True),
        ),
    ]
