# Generated by Django 3.2.7 on 2023-03-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0018_namespace_ng_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='img_source',
            field=models.CharField(choices=[('https://bossdb-open-data.s3.amazonaws.com/iarpa_microns/minnie/minnie65/em', 'Minnie65'), ('gs://microns_public_datasets/pinky100_v0/son_of_alignment_v15_rechunked', 'Pinky'), ('N/A', 'Other')], default='https://bossdb-open-data.s3.amazonaws.com/iarpa_microns/minnie/minnie65/em', max_length=300),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='pcg_source',
            field=models.CharField(choices=[('https://minnie.microns-daf.com/segmentation/table/minnie3_v1', 'Minnie65'), ('https://minnie.microns-daf.com/segmentation/table/pinky_v2_microns_sandbox', 'Pinky'), ('N/A', 'Other')], default='https://minnie.microns-daf.com/segmentation/table/minnie3_v1', max_length=300),
        ),
    ]
