# Generated by Django 4.2.11 on 2025-01-24 18:17

from django.db import migrations, models
import django.db.models.deletion
import workspace.validators


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("workspace", "0022_alter_namespace_ng_host"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "bucket_assignee",
                    models.CharField(
                        help_text="Assignee string to in the queue for this task bucket",
                        max_length=50,
                        unique=True,
                        validators=[workspace.validators.no_whitespace],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="namespace",
            name="expert_pull_from",
        ),
        migrations.RemoveField(
            model_name="namespace",
            name="expert_push_to",
        ),
        migrations.RemoveField(
            model_name="namespace",
            name="intermediate_pull_from",
        ),
        migrations.RemoveField(
            model_name="namespace",
            name="intermediate_push_to",
        ),
        migrations.RemoveField(
            model_name="namespace",
            name="novice_pull_from",
        ),
        migrations.RemoveField(
            model_name="namespace",
            name="novice_push_to",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="expert_namespaces",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="intermediate_namespaces",
        ),
        migrations.CreateModel(
            name="NamespaceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("push", "Push Tasks to"),
                            ("pull", "Pull tasks from"),
                        ],
                        default="pull",
                        help_text="Determines if this rule provides a source or sink for tasks in the queue",
                        max_length=10,
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.namespace",
                    ),
                ),
                (
                    "task_bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.taskbucket",
                    ),
                ),
            ],
            options={
                "unique_together": {("namespace", "action", "task_bucket")},
            },
        ),
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "namespace_rule",
                    models.ManyToManyField(blank=True, to="workspace.namespacerule"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="namespace",
            name="default_pull_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the default pull rule for this namespace. Must be set after the namespace is created.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_pull_for_namespace",
                to="workspace.namespacerule",
            ),
        ),
        migrations.AddField(
            model_name="namespace",
            name="default_push_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the default push rule for this namespace. Must be set after the namespace is created.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_push_for_namespace",
                to="workspace.namespacerule",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="namespace_rule",
            field=models.ManyToManyField(blank=True, to="workspace.namespacerule"),
        ),
    ]
