# Generated by Django 4.2.11 on 2025-03-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0023_taskbucket_remove_namespace_expert_pull_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namespace",
            name="pcg_source",
            field=models.CharField(
                choices=[
                    (
                        "https://minnie.microns-daf.com/segmentation/table/minnie3_v1",
                        "Minnie65",
                    ),
                    (
                        "https://minnie.microns-daf.com/segmentation/table/pinky_v2_microns_sandbox",
                        "Pinky",
                    ),
                    (
                        "https://minnie.microns-daf.com/segmentation/table/minnie65_public",
                        "Minnie65 Public (read-only)",
                    ),
                    ("N/A", "Other"),
                ],
                default="https://minnie.microns-daf.com/segmentation/table/minnie3_v1",
                max_length=300,
            ),
        ),
    ]
