# Generated by Django 4.2.11 on 2025-03-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0024_alter_namespace_pcg_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="namespace",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                verbose_name="Demonstration only? (Submitting does not patch task)",
            ),
        ),
    ]
