# Generated by Django 4.2.11 on 2025-04-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0025_namespace_is_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="namespace",
            name="ng_state_plugin",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("test", "Test")],
                default="",
                max_length=300,
            ),
        ),
    ]
