# Generated by Django 4.2.11 on 2025-04-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0025_namespace_is_demo"),
    ]

    operations = [
        migrations.CreateModel(
            name="NeuroglancerPlugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("default_plugin_params", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="namespace",
            name="plugin_params",
            field=models.JSONField(
                blank=True,
                help_text="Override the default plugin parameters (specified in NeuroglancerPlugin) with namespace-specific values. Provided values will update/override the defaults.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="namespace",
            name="ng_state_plugin",
            field=models.ForeignKey(
                blank=True,
                help_text="Neuroglancer plugin to use for this namespace. If not set, no plugin will be used.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ng_state_plugin",
                to="workspace.neuroglancerplugin",
            ),
        ),
    ]
