# Generated by Django 4.2.11 on 2026-05-20 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0027_userprofile_recent_tags_forcedchoicebutton_palette"),
    ]

    operations = [
        migrations.CreateModel(
            name="Datastack",
            fields=[
                (
                    "datastack_name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cave_url",
                    models.URLField(
                        help_text="CAVE deployment URL (e.g., https://minnie.microns-daf.com)"
                    ),
                ),
                (
                    "cave_datastack",
                    models.CharField(
                        help_text="Datastack name in CAVE (e.g., minnie65_phase3_v1)",
                        max_length=200,
                    ),
                ),
                (
                    "image_source",
                    models.URLField(help_text="Image layer source (precomputed://...)"),
                ),
                (
                    "segmentation_source",
                    models.URLField(help_text="Segmentation source (graphene://...)"),
                ),
                (
                    "table_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Table name mappings (synapses, nuclei, cell_classes, etc.)",
                    ),
                ),
                (
                    "viewer_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Viewer contrast settings and other options",
                    ),
                ),
                (
                    "auth_token_env_var",
                    models.CharField(
                        default="CAVECLIENT_TOKEN",
                        help_text="Environment variable name for CAVE auth token",
                        max_length=100,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Datastack",
                "verbose_name_plural": "Datastacks",
            },
        ),
        migrations.AddField(
            model_name="namespace",
            name="datastack",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Override default datastack for this namespace. If not set, default datastack (minnie65) is used.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspace.datastack",
            ),
        ),
    ]
