# Generated by Django 3.2.7 on 2022-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default=None, max_length=50)),
                ("enabled", models.BooleanField(default=False)),
                ("alpha_selected", models.CharField(default="0.85", max_length=10)),
                ("alpha_3d", models.CharField(default="0.5", max_length=10)),
                ("layout", models.CharField(default="xy-3d", max_length=10)),
            ],
        ),
    ]
