# Generated by Django 3.2.7 on 2022-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=10)),
                ('alpha_selected', models.CharField(default='0.6', max_length=10)),
                ('alpha_3d', models.CharField(default='0.3', max_length=10)),
                ('layout', models.CharField(default='4panel', max_length=10)),
            ],
        ),
    ]
