# Generated by Django 3.2.7 on 2022-02-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='alpha_3d',
            field=models.CharField(default='0.5', max_length=10),
        ),
        migrations.AlterField(
            model_name='config',
            name='alpha_selected',
            field=models.CharField(default='0.75', max_length=10),
        ),
        migrations.AlterField(
            model_name='config',
            name='layout',
            field=models.CharField(default='xy-3d', max_length=10),
        ),
        migrations.AlterField(
            model_name='config',
            name='user',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
