# Generated by Django 3.2.7 on 2022-01-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='alpha_3d',
            field=models.CharField(default='0.3', max_length=10),
        ),
        migrations.AlterField(
            model_name='config',
            name='alpha_selected',
            field=models.CharField(default='0.6', max_length=10),
        ),
    ]
