# Generated by Django 3.2.7 on 2022-03-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0002_auto_20220222_1313"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="annotation_color",
            field=models.CharField(default="#ffff00", max_length=10),
        ),
    ]
