# Generated by Django 3.2.7 on 2022-01-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20220131_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='layout',
            field=models.CharField(default='4panel', max_length=10),
        ),
    ]
