# Generated by Django 3.2.7 on 2022-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_auto_20220314_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='annotation_color_palette',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='annotation_color_palette_switch',
            field=models.BooleanField(default=False),
        ),
    ]
