# Generated by Django 3.2.7 on 2022-04-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_auto_20220314_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='annotation_color_switch',
            new_name='annotation_color_palette_switch',
        ),
        migrations.RemoveField(
            model_name='config',
            name='annotation_color',
        ),
        migrations.AddField(
            model_name='config',
            name='annotation_color_palette',
            field=models.CharField(blank=True, default='palette1', max_length=10, null=True),
        ),
    ]
