# Generated by Django 3.2.7 on 2022-04-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_auto_20220314_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='show_slices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='show_slices_switch',
            field=models.BooleanField(default=False),
        ),
    ]
