# Generated by Django 3.2.7 on 2022-04-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_auto_20220420_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='annotation_color_palette',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
