# Generated by Django 3.2.7 on 2022-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0007_alter_config_annotation_color_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='annotation_color_palette',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
